"""The two arms under comparison.

    Flow 1:  S2 RGB 48² @10m → PixelDiT → 1584² @0.303m → DINOv3 → DPT → 960² @0.5m
    Flow 2:  S2 RGB 48² @10m → bicubic  → 1584² @0.303m → DINOv3 → DPT → 960² @0.5m

They are deliberately the same shape end to end. Both hand DINOv3 a 1584x1584
image and get back four 99x99x1024 token maps; both feed an identically
configured DPT head. The only difference in the whole system is whether those
1584x1584 pixels were generated by PixelDiT or stretched by bicubic -- so any
gap in the final numbers is attributable to the features, not to capacity.

Flow 1 reads its super-resolved images from a cache rather than sampling them
here: the 50-step sampler costs ~3.4 s per patch, which is thousands of times
the cost of everything else and cannot sit inside a training loop. See
`scripts/cache_sr.py`.
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F

from ..constants import HR_SIZE, LABEL_SIZE
from .dinov3 import FrozenDINOv3
from .dpt import DPTHead
from .pixeldit import to_unit_range
from .seedsr_decoder import SeedSRDecoder


def bicubic_to_hr(lr01: torch.Tensor, size: int = HR_SIZE) -> torch.Tensor:
    """(B, 3, 48, 48) in [0, 1] -> (B, 3, 1584, 1584) in [0, 1].

    The baseline's entire 'super-resolution' step. It changes the pixel count
    to match flow 1 and adds no information, which is the point.
    """
    out = F.interpolate(lr01, size=(size, size), mode="bicubic", align_corners=False)
    return out.clamp(0, 1)


def normalize_rgb(
    lr: torch.Tensor,
    lo: torch.Tensor | None = None,
    scale: torch.Tensor | None = None,
    mode: str = "per-image",
) -> torch.Tensor:
    """Raw band values -> [0, 1] for flow 2's DINOv3 input.

    Per-image by default, and deliberately NOT the "stats" default PixelDiT
    conditioning uses. The two serve different consumers: PixelDiT wants
    absolute reflectance, whereas DINOv3 wants a well-exposed picture. In
    flow 1 DINOv3 receives PixelDiT's output, which is already a natural
    full-range RGB image; applying the training stretch here would hand
    flow 2's DINOv3 an image confined to roughly [0, 0.2] and cripple the
    baseline for no principled reason.
    """
    return to_unit_range(lr, lo, scale, mode=mode)


class SegmentationFlow(nn.Module):
    """Frozen DINOv3 + trainable DPT head, shared by both arms.

    Args:
        encoder: the frozen DINOv3 wrapper (shared between flows if you like --
            it holds no per-flow state).
        out_size: spatial size of the logits, 960 for the 0.5 m grid.
    """

    def __init__(
        self,
        encoder: FrozenDINOv3 | None = None,
        out_size: int = LABEL_SIZE,
        fusion_channels: int = 256,
        num_classes: int = 1,
        decoder: str = "seedsr",
    ) -> None:
        super().__init__()
        self.encoder = encoder if encoder is not None else FrozenDINOv3()
        self.decoder_kind = decoder
        if decoder == "seedsr":
            # SEED-SR-style: transposed-conv blocks, SFT conditioning on the LR
            # input, late cross-attention. Needs `condition` at forward time.
            self.head = SeedSRDecoder(
                in_channels=self.encoder.embed_dim,
                num_classes=num_classes,
                out_size=out_size,
            )
        elif decoder == "dpt":
            self.head = DPTHead(
                in_channels=self.encoder.embed_dim,
                fusion_channels=fusion_channels,
                num_classes=num_classes,
                out_size=out_size,
            )
        else:
            raise ValueError(f"unknown decoder {decoder!r}, expected 'seedsr' or 'dpt'")

    def forward(self, hr01: torch.Tensor, condition: torch.Tensor | None = None) -> torch.Tensor:
        """(B, 3, 1584, 1584) in [0, 1] -> (B, num_classes, 960, 960) logits.

        ``condition`` is the LR S2 window in [0, 1], standing in for SEED-SR's
        ``e_l``; required by the seedsr decoder, ignored by dpt.
        """
        features = self.encoder(hr01)
        if self.decoder_kind == "seedsr":
            if condition is None:
                raise ValueError("the seedsr decoder needs `condition` (the LR image)")
            # the HR image also goes in, feeding the high-resolution stem
            return self.head(features, condition, image=hr01)
        return self.head(features)

    def trainable_parameters(self):
        return self.head.parameters()


def hr_from_batch(
    batch: dict,
    flow: int,
    lo: torch.Tensor | None = None,
    scale: torch.Tensor | None = None,
    norm: str = "per-image",
    device: str | torch.device | None = None,
) -> torch.Tensor:
    """Produce the 1584x1584 [0, 1] image each flow feeds to DINOv3.

    Flow 1 takes the cached PixelDiT output; flow 2 stretches the raw input.
    Both end up in the same range and shape.

    Flow 2 is upsampled *on the target device*, not on the CPU: the 48x48
    input is ~1000x smaller than the 1584x1584 result, so normalizing and
    interpolating after the transfer moves 7.5 MB/sample less over PCIe and
    keeps a bicubic resize off the dataloader's critical path.
    """
    if flow == 1:
        if "sr" not in batch:
            raise KeyError("flow 1 needs a cached 'sr' tensor -- run scripts/cache_sr.py")
        sr = batch["sr"]
        return sr.to(device, non_blocking=True) if device is not None else sr
    if flow == 2:
        lr = batch["lr"]
        if device is not None:
            lr = lr.to(device, non_blocking=True)
        return bicubic_to_hr(normalize_rgb(lr, lo, scale, mode=norm))
    raise ValueError(f"unknown flow {flow!r}, expected 1 or 2")


def condition_from_batch(
    batch: dict,
    lo: torch.Tensor | None = None,
    scale: torch.Tensor | None = None,
    norm: str = "per-image",
    device: str | torch.device | None = None,
) -> torch.Tensor:
    """The LR S2 window in [0, 1] -- SEED-SR's ``e_l`` stand-in for SFT conditioning.

    Identical for both arms by construction: it is the same 48x48 input either
    way, so it adds no asymmetry to the comparison.
    """
    lr = batch["lr"]
    if device is not None:
        lr = lr.to(device, non_blocking=True)
    return normalize_rgb(lr, lo, scale, mode=norm)
